import { useState, useEffect } from 'react'
import "./HomePage.css"
import casabonita from "../../assets/casabinita.svg";
import casafeia from "../../assets/casafeia.svg";
import arrow from "../../assets/arrow.svg";
import { useNavigate } from 'react-router-dom';

function HomePage() {
  // In a React component (e.g., App.js)
  const [message, setMessage] = useState('');
  const navigation = useNavigate();

  return (
    <div className='homepage-container'>
      <div className='homepage-content'>
        <h1 className='title'><span className='special-title'>Neural Sketcher</span> is an interactive game where the user plays against a neural network model</h1>
        <p className='text'>Neural Sketcher is an interactive game where the user plays against a neural network model. in the game, the user is prompted to draw an element of the everyday-life, and if, at the end, the AI model successfully classifies it, the user wins the round, whereas if it gets wrong, the user loses a life-point. At the end of the game, all drawings generated by the user will be used to train the model classifier.</p>
        <div className='example-container'>
          <div className='image-alt'>
            <img src={casafeia} alt='sketchy house' className='example-img' />
            <p className='alt-text'>Your drawing</p>
          </div>
          <img src={arrow} alt='arrow' />
          <div className='image-alt'>
            <img src={casabonita} alt='pretty house' className='example-img' />
            <p className='alt-text'>How model classifies</p>
          </div>
        </div>
        <p>THE MODEL CAN IDENTIFY <strong>YOUR DRAWING</strong> AND USE IT TO <strong>TRAIN THE MACHINE</strong> </p>
        <button onClick={()=>{navigation("/board")}} className='play'>PLAY GAME</button>
      </div>
    </div>
  );
}

export default HomePage
