import { useState, useEffect } from 'react'
import "./HomePage.css"
import casabonita from "../../assets/casabinita.svg";
import casafeia from "../../assets/casafeia.svg";
import arrow from "../../assets/arrow.svg";
import { useNavigate } from 'react-router-dom';

function HomePage() {
  // In a React component (e.g., App.js)
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false)
  const [backendState, setBackendState] = useState(false)
  const navigation = useNavigate();

  const playGame = async () => {
    setLoading(true);
    let isBackendReady = false;

    try {
      const response = await fetch("http://127.0.0.1:8000/data");

      if (response.ok) {
        console.log("Backend check successful. Navigating...");
        setBackendState(true);
        isBackendReady = true;
      } else {
        console.log(`Backend responded with an error: ${response.status}`);
        setBackendState(false);
      }
    } catch (error) {
      console.log("Backend did not respond! Cannot start game.", error);
      alert("An error on the server occurred and backend could not be started correctly!")
      setBackendState(false);
    } finally {
      setLoading(false);
    }
    if (isBackendReady) {
      navigation("/board");
    }
  };

  useEffect(() => {
  const checkBackendStatus = async () => {
    setLoading(true);
    try {
      const response = await fetch("http://127.0.0.1:8000/data");

      if (response.ok) {
        console.log("Backend is running and responded successfully!");
        setBackendState(true);
      } else {
        console.log(`Backend responded with an error: ${response.status}`);
        setBackendState(false);
      }
    } catch (error) {
      console.log("Backend did not respond! Server might be down.", error);
      setBackendState(false);
    } finally {
      setLoading(false);
    }
  };

  checkBackendStatus();
}, []);

  return (
    <div className='homepage-container'>
      {loading ? <div className='loading-overlay'><div className='loader'></div></div> : <div className='loading-overlay innactive' />}
      <div className='homepage-content'>
        <h1 className='title'><span className='special-title'>Neural Sketcher</span> is an interactive game where the user plays against a neural network model</h1>
        <p className='text'>In the game, the user is prompted to draw an element of the everyday-life, and if, at the end, the AI model successfully classifies it, the user wins the round, whereas if it gets wrong, the user loses a life-point. At the end of the game, all drawings generated by the user will be used to train the model classifier.</p>
        <div className='example-container'>
          <div className='image-alt'>
            <img src={casafeia} alt='sketchy house' className='example-img' />
            <p className='alt-text'>Your drawing</p>
          </div>
          <img src={arrow} alt='arrow' />
          <div className='image-alt'>
            <img src={casabonita} alt='pretty house' className='example-img' />
            <p className='alt-text'>How model classifies</p>
          </div>
        </div>
        <p className='text'>THE MODEL CAN IDENTIFY <strong>YOUR DRAWING</strong> AND USE IT TO <strong>TRAIN THE MACHINE</strong> </p>
        <button onClick={playGame} className='play'>PLAY GAME</button>
      </div>
    </div>
  );
}

export default HomePage
